# AppId 的值唯一标识此应用。
# 不要在其他应用的安装程序中使用相同的 AppId 值。
# 以下为示例代码，实际根据你的项目进行替换
app_id: 5B566538-42B1-4826-A479-AF079F24A6DD
publisher: Wen Xuan
display_name: 终端称打印一体机
use_previous_group: false
create_desktop_icon: true
install_dir_name: 终端称打印一体机
locales:
  - en
  - zh